### PR TITLE
Upgraded MongoDB driver dependency to mongodb-driver-legacy 4.11.3

### PR DESCRIPTION
**Pull request by jyemin**
* Use mongodb-driver-legacy since mongo-java-driver uber jar is not published as of 4.0.
* Replace find modifiers, which were removed in 4.0, with calls to `FindIterable` methods
* Remove support for $maxScan, which is no longer supported by MongoDB
* Remove support for $explain.  The only way to explain with the 4.x driver is by calling `FindIterable#explain`.  We could do that, and then use `SingleTupleIterator`, but is it worth it?  Is explain only supported by OGM as a native query?
* Handle breaking changes in WriteConcern class
* Handle breaking changes related to MongoCredential

One big issue is that I can't get the tests to all pass even on the main branch, so I can't tell if all these changes are correct.  I'm also unsure how to test against, say, MongoDB 7.0.

### CODE REVIEW

**Comment by Sanne** [comment]
Thanks! Looks very reasonable - but it seems CI jobs are no longer being triggered; I'll need to ask my team mates about it.

**Comment by jyemin** [comment]
> it seems CI jobs are no longer being triggered; I'll need to ask my team mates about it.

@Sanne , maybe because this PR is against our fork?  Happy to open it against https://github.com/hibernate/hibernate-ogm instead.  I was holding off because I wanted it go through some review first from MongoDB driver engineers.

**Comment by Sanne** [comment]
@jyemin ah right I hadn't realized!
yes please, don't worry and feel free to send any PRs to the reference fork.

**Comment by jyemin** [comment]
Done: https://github.com/hibernate/hibernate-ogm/pull/1127

**Pull request closed without merging**
